### ISSUE TITLE
Test helloWorld.pl

### ISSUE THREAD

**Issue by philiprbrenan** [mmonroe-ryffine/teamperl#1]
Please use Git hub to download this project and see if you can run helloWorld.pl on your mac?

**Comment by mmonroe-ryffine** [comment]
Run!
![image](https://user-images.githubusercontent.com/26390198/31409091-84ecb398-adbf-11e7-91ef-c5f957eb1260.png)

**Comment by philiprbrenan** [comment]
Please modify it to say "Hello to you too" and then try and save it - GitHub should object as I have changed the file since you downloaded it.  We can then do a merge.

**Comment by mmonroe-ryffine** [comment]
Done and merged! Is the merge what you expected?

**Comment by philiprbrenan** [comment]
On GitHub I see: 
![github1](https://user-images.githubusercontent.com/7548378/31410066-c865f8c8-ae05-11e7-9244-7626f4104005.png)

I would expect to either see your code in branch master, or better a conflict between the two files?  Have you pushed?

**Comment by mmonroe-ryffine** [comment]
I did push, sorry! I made the changes on my desktop and then tried to sync to the shared repo, it wouldn't let me commit without doing the merge so I just went ahead.

**Comment by philiprbrenan** [comment]
So why do I not see your code?  Why do I see just my code?  I have refreshed the  browser! What do you see at: https://github.com/mmonroe-ryffine/teamperl/blob/master/helloWorld.pl ?

**Comment by mmonroe-ryffine** [comment]
My bad! I merged, committed, and then forgot to push back up. Check it out now.

**Comment by philiprbrenan** [comment]
Success!
