### ISSUE TITLE
Reading parameters from the command line.

### ISSUE THREAD

**Issue by philiprbrenan** [mmonroe-ryffine/teamperl#2]
May I propose that you now modify the program to say Hello to whomever you mention on the command line, like this:

perl helloWorld.pl Mars

to produce:

Hello Mars

Or  Venus etc.?

**Comment by mmonroe-ryffine** [comment]
I'm not quite sure how to run the command so that you can type the name directly after. But check out the code I did write.

So far my terminal thinks that Mars is the input to an argument (name of a file).

**Comment by philiprbrenan** [comment]
Your code is excellent, it solves a different problem: read the name from STDIN - which would have been the next task.  But to get parameters from the command line (which is easier for the user) you need to use @ARGV   Please try a search like: perldoc @ARGV from the web equivalent of the command line?  The @ARGV should be in uppercase - for some reason GitHub is making it lowercase.

**Comment by mmonroe-ryffine** [comment]
Ok, check the new code out! I'm also going to take notes on what I'm learning in a new file called perlNotes.pl if you're ever curious about what I think each command does.

**Comment by philiprbrenan** [comment]
Amazing!  It works brilliantly but for all the wrong reasons!

To see this please do either of the following:

(a) assume there are two names on the command line and that we want to print the first name on line 1 of the output and the second name on line 2.  So perhaps the use enters:

 perl helloWorld.pl Titan Callista

and we want as output:

Hello Titan
Hello Callista

or (b) see the latest version where I have added use strict and use warning to tell Perl to be more demanding of the programmer.

**Comment by mmonroe-ryffine** [comment]
Ok I've tried a couple things and I think I need a bit of help. I've learned a lot about ARGV, but not in a super basic, use-it-right-now kind of way.

Here's the code I expect to work:
`my $name = $ARGV[2];`

`say STDERR "Hello $name";`

I think this code says: Here's a new variable, $name. $name is the third spot on the command line ($ perl script.pl third_available_spot). Now that you know what $name is, say it back out.

Can you tell me the assumption I've made wrong?

Btw, I've also tried "my $name = $ARGV + 2," and removing the "my" so that it's just "name = $ARGV[2]/$ARGV + 2. Either way it just outputs the number 2.

**Comment by mmonroe-ryffine** [comment]
Also I just noticed you gave me assignment b, which I intend to do. But I'd love to get un-stuck on a) first.

**Comment by philiprbrenan** [comment]
As is so often the case in programming, a very near miss, might as well be a miss by a mile.  You logic is impeccable, except for your discussion of the number 2.  Why 2? Perhaps Perl  made some helpful changes to the command line  before it put it into @ARGV for you.  Perhaps some other numbers might be worth checking, for example: -1, 0, 1 - always useful numbers to test with when an unknown number is needed.    

(c) Please try with each of these numbers and see if any of them work better for you.

(d) Please try:

say STDERR "ARGV= ", @ARGV;

(e) Please try:

use Data::Dump qw(dump);
say STDERR dump(@ARGV);

(f) Please try:

use Data::Dump qw(dump);
say STDERR dump([@ARGV]);

(g) suppose now we wanted to run perl in warn mode:

perl -w helloWord.pl Titania

Will this cause problems in your code?

These are all useful actions to take when trying to find out what the program is actually doing as opposed to what we hope and pray it is doing.

**Comment by mmonroe-ryffine** [comment]
I'll start with c) and explain why I thought putting in the number 2 would work. Online, it says that the first argument in the command line is given the number ARGV[0]. So, from that I assumed that the command line arguments were wired like this:

perl helloWorld.pl Moon
ARGV[0] = perl
ARGV[1] = helloWorld.pl
ARGV[2] = Moon

So in my experimentation, ARGV[-1] worked. Is this because it's counting backwards from the right side of the command line?

**Comment by philiprbrenan** [comment]
Yes - that is an excellent conclusion!  And what about the other test numbers: do any of them work and if they do/not why/not?

**Comment by mmonroe-ryffine** [comment]
I'm working on those now! Why doesn't counting forward work as I expected?

d) Code is now
`my $name = $ARGV[-1];`
`say STDERR "ARGV= ", @ARGV;`

Output is 'ARGV= Moon'.  If I run two arguments, like Moon Sun, @ARGV overrides the [-1] and outputs both as ARGV= MoonSun.

**Comment by philiprbrenan** [comment]
We need the results if your tests with 0 and 1 in (c) to draw any firm conclusions.  I could of course just tell you the answer but then you would forget it immediately and learn nothing. This way you learn the most important part of computing: planning experiments, carrying them out, evaluating the results to determine what is going on, iterating as necessary until you have a theory that stands up to experimental evidence.

**Comment by philiprbrenan** [comment]
As you will need to do a lot of experiments you will need good tools set up properly so that you can quickly and easily perform lots of experiments and thus make good use of your time --- one of the many advantages of Perl is that it supports this kind of activity.

**Comment by mmonroe-ryffine** [comment]
d) Okay I think I get it. The first argument, 0, starts after the script is referenced!

e) Code is now 
`use Data::Dump qw(dump);`
`say STDERR dump(@ARGV);`

Dumping spits each argument back out in a neat list. There's lots of mentions of dump in this code and I'm interested in what each one does and why they're all needed to dump the string. Can you let me know if I'm wrong?

Data::Dump -- 
Is a library full of the commands used to output pretty lists. You need to declare the library before you can use the functions inside it, aka qw().

qw(dump) --
- Function qw() returns a quoted list
- (dump) is the input to that list

dump()--
Displays the dumped data for the user.

**Comment by philiprbrenan** [comment]
(d, e) Excellent! Leaving (a, b, c, f, g) to complete!  Perl has a philosophy of: "There is more than one way to do it" vs Python: "there is only one way to do it".  This is what makes Perl code so malleable and thus potentially dangerous in the hands of beginners as things seem to work but for the wrong reasons which only become visible much  later on - when the space probe is entering the Martian atmosphere and it is to late to do anything about it.,

**Comment by mmonroe-ryffine** [comment]
Hah okay! Well here's what's missing:

a) Output each on its own line:
Hello Titan
Hello Callista
`my $name1 = $ARGV[0];`
`my $name2 = $ARGV[1];`
`say STDERR "Hello $name1";`
`say STDERR "Hello $name2";`

b) see the latest version where I have added use strict and use warning to tell Perl to be more demanding of the programmer.

use warnings--
Enables warnings on specific blocks of code. Apparently the better, more useful version of -w. It calls out errors in your code, or potential errors in code. You can overcome these warnings by coding better.

FATAL => all--
Treats warnings as fatal errors and shuts down the program at the first error. It forces you to fix the bugs that your customers will likely encounter.

use strict--
Disables expressions that are difficult to debug or that may not behave as expected.

c) Please try with each of these numbers (-1, 0, 1) and see if any of them work better for you. 
perl helloWorld.pl Titan Callista

- Putting 0 in causes it to output correctly (Hello Titan). If you give it two inputs, it gives you the one furthest left.
- Putting 1 in causes it to give the second input, if there is one. (Hello Callista)
- Putting -1 in causes it to give the first input from the left. (Hello Callista)

f) 
use Data::Dump qw(dump);
say STDERR dump([@argv]);
It dumps the input into a quoted list ["Callista", "Titan"]. Luckily I had use strict in the code, which helped me debug my error. I had copied the above text and @argv was lower-case and so was interpreted as an undeclared variable!

g) suppose now we wanted to run perl in warn mode:
perl -w helloWord.pl Titania
You could but it sounds like use warnings is better. The warn mode outputs errors on all parts of the code.

**Comment by philiprbrenan** [comment]
Excellent!
